runtime: python311

env_variables:
  # Import from .env file (you'll set these in Google Cloud Console)
  NEO4J_URI: "neo4j+s://e3671855.databases.neo4j.io"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "c8TtugjdTClI-4LEy1LqVWnSDkj6QHbJo61U9I9yNOI"
  NEO4J_DATABASE: "neo4j"
  
  MILVUS_URI: "https://in03-9ec7c214a18d7a5.serverless.aws-eu-central-1.cloud.zilliz.com"
  MILVUS_TOKEN: "981a4eaaced7dbb49e0a940d97c7e6d0dd728aedf76bd1e6b7f17c99745dadd425f5d3b02812b4a3b6321a35eb2e8e1d15aa1dcf"
  MILVUS_COLLECTION_NAME: "bionexus_embeddings"
  MILVUS_SECURE: "true"
  
  AZURE_SUBSCRIPTION_ID: "1ab50acb-5c33-4470-b5fa-fef2bc8e1cd8"
  AZURE_TEXT_ANALYTICS_ENDPOINT: "https://eastus.api.cognitive.microsoft.com/"
  AZURE_TEXT_ANALYTICS_KEY: "91763b26b4ed446c8f77b982ff4a9ed8"
  AZURE_COMPUTER_VISION_ENDPOINT: "https://eastus.api.cognitive.microsoft.com/"
  AZURE_COMPUTER_VISION_KEY: "91763b26b4ed446c8f77b982ff4a9ed8"
  
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  HOST: "0.0.0.0"
  PORT: "8080"
  WORKERS: "4"
  
  SECRET_KEY: "bionexus-production-secret-key-2024"
  ACCESS_TOKEN_EXPIRE_MINUTES: "480"
  
  BATCH_SIZE: "16"
  QUERY_TIMEOUT: "30"
  SEARCH_LIMIT: "50"
  SENTENCE_TRANSFORMER_MODEL: "all-MiniLM-L6-v2"
  DEVICE: "cpu"

automatic_scaling:
  min_instances: 1
  max_instances: 10